# Generated by Django 2.2.12 on 2020-05-14 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MasterPoltekTedc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.SmallIntegerField(default='045016')),
                ('nama', models.CharField(max_length=100)),
                ('status', models.CharField(default='Aktif', max_length=5)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.CharField(blank=True, max_length=100)),
                ('alamat', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MasterProdi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.SmallIntegerField()),
                ('nama', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('A', 'Aktif'), ('T', 'Tutup')], default='Tutup', max_length=5)),
                ('jejang', models.CharField(choices=[('D1', 'Diploma Satu'), ('D3', 'Diploma Tiga'), ('D4', 'Diploma Empat')], max_length=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
