# Generated by Django 2.2.12 on 2020-05-14 10:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('poltektedc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterpoltektedc',
            name='kota',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='masterprodi',
            name='jejang',
            field=models.CharField(choices=[('D1', 'Diploma 1 (Satu)'), ('D3', 'Diploma 3 (Tiga)'), ('D4', 'Diploma 4 (Empat)')], max_length=2),
        ),
    ]
