# Generated by Django 2.2.12 on 2020-05-14 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poltektedc', '0002_auto_20200514_1015'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='masterprodi',
            options={'ordering': ['nama']},
        ),
    ]
