# Generated by Django 2.2.12 on 2020-07-14 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poltektedc', '0003_auto_20200514_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterpoltektedc',
            name='kode',
            field=models.PositiveIntegerField(default='045016'),
        ),
        migrations.AlterField(
            model_name='masterprodi',
            name='kode',
            field=models.PositiveIntegerField(),
        ),
    ]
