# Generated by Django 2.2.12 on 2020-07-14 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poltektedc', '0004_auto_20200714_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterpoltektedc',
            name='kode',
            field=models.CharField(default='045016', max_length=6),
        ),
    ]
