# Generated by Django 2.2.12 on 2020-07-26 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poltektedc', '0005_auto_20200714_1457'),
    ]

    operations = [
        migrations.RenameField(
            model_name='masterprodi',
            old_name='jejang',
            new_name='jenjang',
        ),
    ]
