# Generated by Django 2.2.12 on 2020-05-14 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuesioner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterfsatu',
            name='kode_pt',
            field=models.IntegerField(default='045016', editable=False),
        ),
    ]
