# Generated by Django 2.2.12 on 2020-05-14 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuesioner', '0002_auto_20200514_0432'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='masterkuesioner',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='masterkuesioner',
            name='judul',
            field=models.CharField(max_length=130),
        ),
    ]
