# Generated by Django 2.2.12 on 2020-05-15 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kuesioner', '0003_auto_20200514_1313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='masterfdua',
            old_name='pertanyaan',
            new_name='sub_pertanyaan',
        ),
        migrations.RenameField(
            model_name='masterkuesioner',
            old_name='judul',
            new_name='pertayaan',
        ),
    ]
