# Generated by Django 2.2.12 on 2020-05-15 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kuesioner', '0004_auto_20200515_0909'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MasterFDua',
            new_name='MasterSubKuesioner',
        ),
    ]
