# Generated by Django 2.2.12 on 2020-05-16 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kuesioner', '0005_auto_20200515_1000'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mastersubkuesioner',
            options={'ordering': ['id']},
        ),
        migrations.RenameField(
            model_name='masterkuesioner',
            old_name='deskripsi',
            new_name='keterangan',
        ),
        migrations.RemoveField(
            model_name='mastersubkuesioner',
            name='master_kuesioner',
        ),
    ]
