# Generated by Django 2.2.12 on 2020-05-18 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kuesioner', '0006_auto_20200516_0931'),
    ]

    operations = [
        migrations.RenameField(
            model_name='masterfsatu',
            old_name='tahun_lulusan',
            new_name='tahun_lulus',
        ),
    ]
