# Generated by Django 2.2.12 on 2020-05-18 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuesioner', '0007_auto_20200518_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterfsatu',
            name='kode_prodi',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='masterfsatu',
            name='nomor_telepon',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='masterfsatu',
            name='tahun_lulus',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
