# Generated by Django 2.2.12 on 2020-06-01 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuesioner', '0009_auto_20200518_1457'),
    ]

    operations = [
        migrations.RenameField(
            model_name='masterkuesioner',
            old_name='pertayaan',
            new_name='pertanyaan',
        ),
        migrations.AlterField(
            model_name='masterfsatu',
            name='kode_prodi',
            field=models.PositiveSmallIntegerField(choices=[(62401, 'Akuntansi'), (57302, 'Komputerisasi Akuntansi'), (22303, 'Konstruksi Bangunan'), (21301, 'Mekanik Industri Dan Desain'), (55301, 'Teknik Informatika'), (21312, 'Teknik Otomasi')]),
        ),
        migrations.AlterField(
            model_name='masterfsatu',
            name='nomor_mahasiswa',
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='masterfsatu',
            name='tahun_lulus',
            field=models.PositiveSmallIntegerField(choices=[(2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020)]),
        ),
    ]
