# Generated by Django 2.2.12 on 2020-06-01 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kuesioner', '0010_auto_20200601_0100'),
    ]

    operations = [
        migrations.AddField(
            model_name='mastersubkuesioner',
            name='master_kuesioner_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kuesioner.MasterKuesioner'),
        ),
    ]
