# Generated by Django 2.2.12 on 2020-06-03 14:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kuesioner', '0011_mastersubkuesioner_master_kuesioner_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='mastersubkuesioner',
            name='kode',
            field=models.CharField(default=django.utils.timezone.now, max_length=5),
            preserve_default=False,
        ),
    ]
