# Generated by Django 2.2.12 on 2020-06-04 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuesioner', '0012_mastersubkuesioner_kode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mastersubkuesioner',
            name='kode',
            field=models.CharField(max_length=7),
        ),
    ]
