# Generated by Django 2.2.12 on 2020-06-05 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kuesioner', '0014_masteropsirespons'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='masterkuesioner',
            options={},
        ),
        migrations.AlterModelOptions(
            name='mastersubkuesioner',
            options={},
        ),
    ]
