# Generated by Django 2.2.12 on 2020-06-05 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kuesioner', '0015_auto_20200605_1012'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='masterkuesioner',
            options={'ordering': ['id']},
        ),
    ]
