# Generated by Django 2.2.12 on 2020-06-05 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuesioner', '0016_auto_20200605_1028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mastersubkuesioner',
            name='master_kuesioner_id',
        ),
        migrations.AddField(
            model_name='mastersubkuesioner',
            name='master_kuesioner_id',
            field=models.ManyToManyField(to='kuesioner.MasterKuesioner'),
        ),
    ]
