# Generated by Django 2.2.12 on 2020-06-05 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuesioner', '0017_auto_20200605_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mastersubkuesioner',
            name='master_kuesioner_id',
            field=models.ManyToManyField(blank=True, null=True, to='kuesioner.MasterKuesioner'),
        ),
    ]
