# Generated by Django 2.2.12 on 2020-06-05 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuesioner', '0018_auto_20200605_1031'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='masteropsirespons',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='mastersubkuesioner',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='masterkuesioner',
            name='pertanyaan',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='masteropsirespons',
            name='opsi_respons',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='mastersubkuesioner',
            name='master_kuesioner_id',
            field=models.ManyToManyField(blank=True, to='kuesioner.MasterKuesioner'),
        ),
        migrations.AlterField(
            model_name='mastersubkuesioner',
            name='sub_pertanyaan',
            field=models.CharField(max_length=150),
        ),
    ]
