# Generated by Django 2.2.12 on 2020-06-06 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuesioner', '0019_auto_20200605_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masteropsirespons',
            name='master_kuesioner_id',
        ),
        migrations.AddField(
            model_name='masteropsirespons',
            name='master_kuesioner_id',
            field=models.ManyToManyField(blank=True, to='kuesioner.MasterKuesioner'),
        ),
    ]
