# Generated by Django 2.2.12 on 2020-06-30 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poltektedc', '0003_auto_20200514_1313'),
        ('kuesioner', '0020_auto_20200606_1416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masterfsatu',
            name='kode_prodi',
        ),
        migrations.RemoveField(
            model_name='masterfsatu',
            name='kode_pt',
        ),
        migrations.AddField(
            model_name='masterfsatu',
            name='master_poltek_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='poltektedc.MasterPoltekTedc'),
        ),
        migrations.AddField(
            model_name='masterfsatu',
            name='master_prodi_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='poltektedc.MasterProdi'),
        ),
    ]
