# Generated by Django 2.2.12 on 2020-07-14 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kuesioner', '0021_auto_20200630_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterfsatu',
            name='master_poltek_id',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='poltektedc.MasterPoltekTedc'),
        ),
    ]
