# Generated by Django 2.2.12 on 2020-09-23 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuesioner', '0022_auto_20200714_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterfsatu',
            name='tahun_lulus',
            field=models.PositiveSmallIntegerField(choices=[(2018, 2018), (2019, 2019), (2020, 2020)]),
        ),
    ]
