# Generated by Django 2.2.12 on 2020-05-18 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lulusan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biodatalulusan',
            name='verifikasi_email',
            field=models.NullBooleanField(default=False),
        ),
    ]
