# Generated by Django 2.2.12 on 2020-07-23 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lulusan', '0002_auto_20200518_0051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biodatalulusan',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='biodatalulusan',
            name='verifikasi_email',
        ),
        migrations.AddField(
            model_name='biodatalulusan',
            name='akun_linkendin',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='biodatalulusan',
            name='foto',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='biodatalulusan',
            name='status',
            field=models.CharField(blank=True, choices=[('Lajang', 'Lajang'), ('Sudah Menikah', 'Sudah Menikah')], max_length=15),
        ),
        migrations.AlterField(
            model_name='biodatalulusan',
            name='alamat',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='biodatalulusan',
            name='angkatan',
            field=models.SmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='biodatalulusan',
            name='jenis_kelamin',
            field=models.CharField(blank=True, choices=[('Perempuan', 'Perempuan'), ('Laki-laki', 'Laki-laki')], max_length=12),
        ),
        migrations.AlterField(
            model_name='biodatalulusan',
            name='pekerjaan',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
