# Generated by Django 2.2.12 on 2020-07-24 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lulusan', '0003_auto_20200723_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biodatalulusan',
            name='tanggal_lahir',
            field=models.DateField(blank=True),
        ),
    ]
