# Generated by Django 2.2.12 on 2020-07-24 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lulusan', '0004_auto_20200724_0642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biodatalulusan',
            name='angkatan',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
    ]
