# Generated by Django 2.2.12 on 2020-07-24 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lulusan', '0005_auto_20200724_0646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biodatalulusan',
            name='angkatan',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='biodatalulusan',
            name='tanggal_lahir',
            field=models.DateField(auto_now_add=True),
        ),
    ]
