# Generated by Django 2.2.12 on 2020-07-26 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lulusan', '0007_auto_20200726_0709'),
    ]

    operations = [
        migrations.RenameField(
            model_name='biodatalulusan',
            old_name='akun_linkendin',
            new_name='akun_linkedin',
        ),
    ]
