# Generated by Django 2.2.12 on 2020-07-26 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lulusan', '0008_auto_20200726_0721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biodatalulusan',
            name='tanggal_lahir',
            field=models.DateField(),
        ),
    ]
