# Generated by Django 2.2.12 on 2020-07-26 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lulusan', '0009_auto_20200726_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biodatalulusan',
            name='tanggal_lahir',
            field=models.DateField(blank=True, null=True),
        ),
    ]
