# Generated by Django 2.2.12 on 2020-09-23 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lulusan', '0010_auto_20200726_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biodatalulusan',
            name='angkatan',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
