# Generated by Django 2.2.12 on 2020-09-19 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kuesioner', '0022_auto_20200714_1438'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponsHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('current_tab', models.SmallIntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, editable=False)),
                ('master_fsatu_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kuesioner.MasterFSatu')),
            ],
        ),
        migrations.CreateModel(
            name='ResponsFTujuhDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respons', models.SmallIntegerField(blank=True, null=True)),
                ('master_kuesioner_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kuesioner.MasterKuesioner')),
                ('master_subkuesioner_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kuesioner.MasterSubKuesioner')),
                ('respons_header_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='respons.ResponsHeader')),
            ],
        ),
        migrations.CreateModel(
            name='ResponsFTujuhbelasBDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respons', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('master_kuesioner_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kuesioner.MasterKuesioner')),
                ('master_subkuesioner_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kuesioner.MasterSubKuesioner')),
                ('respons_header_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='respons.ResponsHeader')),
            ],
        ),
        migrations.CreateModel(
            name='ResponsFTujuhbelasADetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respons', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('master_kuesioner_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kuesioner.MasterKuesioner')),
                ('master_subkuesioner_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kuesioner.MasterSubKuesioner')),
                ('respons_header_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='respons.ResponsHeader')),
            ],
        ),
        migrations.CreateModel(
            name='ResponsFTujuhADetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respons', models.SmallIntegerField(blank=True, null=True)),
                ('master_kuesioner_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kuesioner.MasterKuesioner')),
                ('master_subkuesioner_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kuesioner.MasterSubKuesioner')),
                ('respons_header_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='respons.ResponsHeader')),
            ],
        ),
        migrations.CreateModel(
            name='ResponsFTigaDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respons', models.SmallIntegerField(blank=True, null=True)),
                ('keterangan', models.CharField(blank=True, max_length=30, null=True)),
                ('master_kuesioner_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kuesioner.MasterKuesioner')),
                ('respons_header_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='respons.ResponsHeader')),
            ],
        ),
        migrations.CreateModel(
            name='ResponsFTigabelasDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respons', models.BigIntegerField(blank=True, default=0, null=True)),
                ('master_kuesioner_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kuesioner.MasterKuesioner')),
                ('master_subkuesioner_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kuesioner.MasterSubKuesioner')),
                ('respons_header_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='respons.ResponsHeader')),
            ],
        ),
        migrations.CreateModel(
            name='ResponsFSepuluhDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respons', models.CharField(blank=True, max_length=100, null=True)),
                ('master_kuesioner_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kuesioner.MasterKuesioner')),
                ('respons_header_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='respons.ResponsHeader')),
            ],
        ),
        migrations.CreateModel(
            name='ResponsFSembilanDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respons', models.TextField(blank=True, null=True)),
                ('master_kuesioner_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kuesioner.MasterKuesioner')),
                ('respons_header_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='respons.ResponsHeader')),
            ],
        ),
        migrations.CreateModel(
            name='ResponsFSebelasDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respons', models.CharField(blank=True, max_length=100, null=True)),
                ('master_kuesioner_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kuesioner.MasterKuesioner')),
                ('respons_header_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='respons.ResponsHeader')),
            ],
        ),
        migrations.CreateModel(
            name='ResponsFLimaDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respons', models.SmallIntegerField(blank=True, null=True)),
                ('keterangan', models.CharField(blank=True, max_length=30, null=True)),
                ('master_kuesioner_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kuesioner.MasterKuesioner')),
                ('respons_header_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='respons.ResponsHeader')),
            ],
        ),
        migrations.CreateModel(
            name='ResponsFLimabelasDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respons', models.CharField(blank=True, max_length=25, null=True)),
                ('master_kuesioner_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kuesioner.MasterKuesioner')),
                ('respons_header_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='respons.ResponsHeader')),
            ],
        ),
        migrations.CreateModel(
            name='ResponsFEnamDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respons', models.SmallIntegerField(blank=True, null=True)),
                ('master_kuesioner_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kuesioner.MasterKuesioner')),
                ('master_subkuesioner_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kuesioner.MasterSubKuesioner')),
                ('respons_header_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='respons.ResponsHeader')),
            ],
        ),
        migrations.CreateModel(
            name='ResponsFEnambelasDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respons', models.TextField(blank=True, null=True)),
                ('master_kuesioner_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kuesioner.MasterKuesioner')),
                ('respons_header_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='respons.ResponsHeader')),
            ],
        ),
        migrations.CreateModel(
            name='ResponsFEmpatDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respons', models.TextField(blank=True, null=True)),
                ('master_kuesioner_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kuesioner.MasterKuesioner')),
                ('respons_header_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='respons.ResponsHeader')),
            ],
        ),
        migrations.CreateModel(
            name='ResponsFEmpatbelasDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respons', models.CharField(blank=True, max_length=25, null=True)),
                ('master_kuesioner_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kuesioner.MasterKuesioner')),
                ('respons_header_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='respons.ResponsHeader')),
            ],
        ),
        migrations.CreateModel(
            name='ResponsFDuaDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respons', models.CharField(blank=True, default=0, max_length=25, null=True)),
                ('master_kuesioner_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kuesioner.MasterKuesioner')),
                ('master_subkuesioner_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kuesioner.MasterSubKuesioner')),
                ('respons_header_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='respons.ResponsHeader')),
            ],
        ),
        migrations.CreateModel(
            name='ResponsFDelapanDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respons', models.CharField(blank=True, max_length=6, null=True)),
                ('master_kuesioner_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kuesioner.MasterKuesioner')),
                ('respons_header_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='respons.ResponsHeader')),
            ],
        ),
    ]
