# Generated by Django 2.2.12 on 2020-05-16 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kuesioner', '0006_auto_20200516_0931'),
        ('respons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponsFTigaDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respons', models.SmallIntegerField()),
                ('master_kuesioner_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kuesioner.MasterKuesioner')),
                ('master_subkuesioner_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kuesioner.MasterSubKuesioner')),
            ],
        ),
        migrations.CreateModel(
            name='ResponsFDuaDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respons', models.CharField(max_length=25)),
                ('master_kuesioner_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kuesioner.MasterKuesioner')),
                ('master_subkuesioner_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kuesioner.MasterSubKuesioner')),
            ],
        ),
    ]
