# Generated by Django 2.2.12 on 2020-09-19 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('respons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsfduadetail',
            name='respons_dua',
            field=models.CharField(blank=True, default=0, max_length=25, null=True),
        ),
    ]
