# Generated by Django 2.2.12 on 2020-09-19 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('respons', '0002_responsfduadetail_respons_dua'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responsfduadetail',
            name='respons_dua',
        ),
    ]
