# Generated by Django 2.2.12 on 2020-09-19 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('respons', '0003_remove_responsfduadetail_respons_dua'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsheader',
            name='completed',
            field=models.SmallIntegerField(default=0),
        ),
    ]
