# Generated by Django 2.2.12 on 2020-06-09 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('respons', '0003_responsfdelapandetail_responsfempatbelasdetail_responsfempatdetail_responsfenambelasdetail_responsfe'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsfduadetail',
            name='respons_header_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='respons.ResponsHeader'),
        ),
    ]
