# Generated by Django 2.2.12 on 2020-06-15 14:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('respons', '0004_responsfduadetail_respons_header_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responsftigadetail',
            name='master_subkuesioner_id',
        ),
        migrations.AddField(
            model_name='responsftigadetail',
            name='keterangan',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='responsftigadetail',
            name='respons',
            field=models.SmallIntegerField(blank=True),
        ),
    ]
