# Generated by Django 2.2.12 on 2020-09-19 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('respons', '0004_auto_20200919_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsheader',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
