# Generated by Django 2.2.12 on 2020-09-23 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('respons', '0005_auto_20200919_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsheader',
            name='master_fsatu_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kuesioner.MasterFSatu'),
        ),
    ]
