# Generated by Django 2.2.12 on 2020-06-15 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('respons', '0005_auto_20200615_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsftigadetail',
            name='respons_header_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='respons.ResponsHeader'),
        ),
    ]
