# Generated by Django 2.2.12 on 2020-06-16 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kuesioner', '0020_auto_20200606_1416'),
        ('respons', '0008_remove_responsfempatdetail_master_subkuesioner_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsfempatdetail',
            name='master_subkuesioner_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kuesioner.MasterSubKuesioner'),
        ),
    ]
