# Generated by Django 2.2.12 on 2020-06-16 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('respons', '0009_responsfempatdetail_master_subkuesioner_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responsflimadetail',
            name='master_subkuesioner_id',
        ),
    ]
