# Generated by Django 2.2.12 on 2020-06-16 16:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('respons', '0010_remove_responsflimadetail_master_subkuesioner_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsflimadetail',
            name='keterangan',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
    ]
