# Generated by Django 2.2.12 on 2020-06-16 16:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('respons', '0013_responsfenamdetail_respons_header_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsfduadetail',
            name='respons_header_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='respons.ResponsHeader'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='responsfempatdetail',
            name='respons_header_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='respons.ResponsHeader'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='responsflimadetail',
            name='respons_header_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='respons.ResponsHeader'),
        ),
        migrations.AlterField(
            model_name='responsftigadetail',
            name='respons_header_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='respons.ResponsHeader'),
        ),
    ]
