# Generated by Django 2.2.12 on 2020-06-16 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('respons', '0014_auto_20200616_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsfduadetail',
            name='respons_header_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='respons.ResponsHeader'),
        ),
        migrations.AlterField(
            model_name='responsfempatdetail',
            name='respons_header_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='respons.ResponsHeader'),
        ),
        migrations.AlterField(
            model_name='responsflimadetail',
            name='respons_header_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='respons.ResponsHeader'),
        ),
        migrations.AlterField(
            model_name='responsftigadetail',
            name='respons_header_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='respons.ResponsHeader'),
        ),
    ]
