# Generated by Django 2.2.12 on 2020-06-16 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('respons', '0015_auto_20200616_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responsfduadetail',
            name='respons_header_id',
        ),
        migrations.RemoveField(
            model_name='responsfempatdetail',
            name='respons_header_id',
        ),
        migrations.RemoveField(
            model_name='responsfenamdetail',
            name='respons_header_id',
        ),
        migrations.RemoveField(
            model_name='responsflimadetail',
            name='respons_header_id',
        ),
        migrations.RemoveField(
            model_name='responsftigadetail',
            name='respons_header_id',
        ),
    ]
