# Generated by Django 2.2.12 on 2020-06-16 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('respons', '0016_auto_20200616_1624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responsfduadetail',
            name='master_kuesioner_id',
        ),
        migrations.RemoveField(
            model_name='responsfduadetail',
            name='master_subkuesioner_id',
        ),
        migrations.RemoveField(
            model_name='responsfduadetail',
            name='respons',
        ),
        migrations.RemoveField(
            model_name='responsfempatdetail',
            name='master_kuesioner_id',
        ),
        migrations.RemoveField(
            model_name='responsfempatdetail',
            name='master_subkuesioner_id',
        ),
        migrations.RemoveField(
            model_name='responsfempatdetail',
            name='respons',
        ),
        migrations.RemoveField(
            model_name='responsfenamdetail',
            name='master_kuesioner_id',
        ),
        migrations.RemoveField(
            model_name='responsfenamdetail',
            name='master_subkuesioner_id',
        ),
        migrations.RemoveField(
            model_name='responsfenamdetail',
            name='respons',
        ),
        migrations.RemoveField(
            model_name='responsflimadetail',
            name='keterangan',
        ),
        migrations.RemoveField(
            model_name='responsflimadetail',
            name='master_kuesioner_id',
        ),
        migrations.RemoveField(
            model_name='responsflimadetail',
            name='respons',
        ),
        migrations.RemoveField(
            model_name='responsftigadetail',
            name='keterangan',
        ),
        migrations.RemoveField(
            model_name='responsftigadetail',
            name='master_kuesioner_id',
        ),
        migrations.RemoveField(
            model_name='responsftigadetail',
            name='respons',
        ),
    ]
