# Generated by Django 2.2.12 on 2020-06-16 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('respons', '0017_auto_20200616_1640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responsheader',
            name='created',
        ),
        migrations.RemoveField(
            model_name='responsheader',
            name='master_fsatu_id',
        ),
        migrations.RemoveField(
            model_name='responsheader',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='responsheader',
            name='updated',
        ),
    ]
