# Generated by Django 2.2.12 on 2020-06-17 03:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kuesioner', '0020_auto_20200606_1416'),
        ('respons', '0018_auto_20200616_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsfduadetail',
            name='master_kuesioner_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kuesioner.MasterKuesioner'),
        ),
        migrations.AddField(
            model_name='responsfduadetail',
            name='master_subkuesioner_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kuesioner.MasterSubKuesioner'),
        ),
        migrations.AddField(
            model_name='responsfduadetail',
            name='respons',
            field=models.CharField(max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='responsfempatdetail',
            name='master_kuesioner_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kuesioner.MasterKuesioner'),
        ),
        migrations.AddField(
            model_name='responsfempatdetail',
            name='master_subkuesioner_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kuesioner.MasterSubKuesioner'),
        ),
        migrations.AddField(
            model_name='responsfempatdetail',
            name='respons',
            field=models.TextField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='responsfenamdetail',
            name='master_kuesioner_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kuesioner.MasterKuesioner'),
        ),
        migrations.AddField(
            model_name='responsfenamdetail',
            name='master_subkuesioner_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kuesioner.MasterSubKuesioner'),
        ),
        migrations.AddField(
            model_name='responsfenamdetail',
            name='respons',
            field=models.SmallIntegerField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='responsflimadetail',
            name='keterangan',
            field=models.CharField(max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='responsflimadetail',
            name='master_kuesioner_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kuesioner.MasterKuesioner'),
        ),
        migrations.AddField(
            model_name='responsflimadetail',
            name='respons',
            field=models.SmallIntegerField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='responsftigadetail',
            name='keterangan',
            field=models.CharField(max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='responsftigadetail',
            name='master_kuesioner_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kuesioner.MasterKuesioner'),
        ),
        migrations.AddField(
            model_name='responsftigadetail',
            name='respons',
            field=models.SmallIntegerField(blank=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='responsheader',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='responsheader',
            name='master_fsatu_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kuesioner.MasterFSatu'),
        ),
        migrations.AddField(
            model_name='responsheader',
            name='slug',
            field=models.SlugField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name='responsheader',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
