# Generated by Django 2.2.12 on 2020-06-17 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('respons', '0019_auto_20200617_0331'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsfduadetail',
            name='respons_header_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='respons.ResponsHeader'),
        ),
    ]
