# Generated by Django 2.2.12 on 2020-06-17 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('respons', '0020_responsfduadetail_respons_header_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsfempatdetail',
            name='respons_header_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='respons.ResponsHeader'),
        ),
        migrations.AddField(
            model_name='responsfenamdetail',
            name='respons_header_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='respons.ResponsHeader'),
        ),
        migrations.AddField(
            model_name='responsflimadetail',
            name='respons_header_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='respons.ResponsHeader'),
        ),
        migrations.AddField(
            model_name='responsftigadetail',
            name='respons_header_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='respons.ResponsHeader'),
        ),
    ]
