# Generated by Django 2.2.12 on 2020-06-17 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kuesioner', '0020_auto_20200606_1416'),
        ('respons', '0021_auto_20200617_0404'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsftujuhdetail',
            name='respons_header_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='respons.ResponsHeader'),
        ),
        migrations.CreateModel(
            name='ResponsFTujuhADetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respons', models.SmallIntegerField()),
                ('master_kuesioner_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kuesioner.MasterKuesioner')),
                ('master_subkuesioner_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kuesioner.MasterSubKuesioner')),
                ('respons_header_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='respons.ResponsHeader')),
            ],
        ),
    ]
