# Generated by Django 2.2.12 on 2020-06-17 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('respons', '0023_auto_20200617_0951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responsfdelapandetail',
            name='master_subkuesioner_id',
        ),
        migrations.RemoveField(
            model_name='responsfsembilandetail',
            name='master_subkuesioner_id',
        ),
        migrations.RemoveField(
            model_name='responsfsepuluhdetail',
            name='master_subkuesioner_id',
        ),
    ]
