# Generated by Django 2.2.12 on 2020-06-17 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('respons', '0024_auto_20200617_1001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responsfempatbelasdetail',
            name='master_subkuesioner_id',
        ),
        migrations.RemoveField(
            model_name='responsfsebelasdetail',
            name='master_subkuesioner_id',
        ),
        migrations.AddField(
            model_name='responsfempatbelasdetail',
            name='respons_header_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='respons.ResponsHeader'),
        ),
        migrations.AddField(
            model_name='responsfsebelasdetail',
            name='respons_header_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='respons.ResponsHeader'),
        ),
        migrations.AddField(
            model_name='responsftigabelasdetail',
            name='respons_header_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='respons.ResponsHeader'),
        ),
    ]
