# Generated by Django 2.2.12 on 2020-06-22 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kuesioner', '0020_auto_20200606_1416'),
        ('respons', '0026_auto_20200619_1003'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ResponsFTujuhbelasADetail',
            new_name='ResponsFTujuhAbelasADetail',
        ),
        migrations.CreateModel(
            name='ResponsFTujuhBbelasADetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respons', models.SmallIntegerField()),
                ('master_kuesioner_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kuesioner.MasterKuesioner')),
                ('master_subkuesioner_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kuesioner.MasterSubKuesioner')),
                ('respons_header_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='respons.ResponsHeader')),
            ],
        ),
    ]
