# Generated by Django 2.2.12 on 2020-06-22 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('respons', '0028_auto_20200622_0703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responsfempatdetail',
            name='master_subkuesioner_id',
        ),
    ]
