# Generated by Django 2.2.12 on 2020-07-04 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuesioner', '0021_auto_20200630_1455'),
        ('respons', '0030_auto_20200702_0254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responsfempatdetail',
            name='respons',
        ),
        migrations.AddField(
            model_name='responsfempatdetail',
            name='respons',
            field=models.ManyToManyField(to='kuesioner.MasterOpsiRespons'),
        ),
    ]
