# Generated by Django 2.2.12 on 2020-07-04 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('respons', '0032_auto_20200704_0705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsfempatdetail',
            name='respons',
            field=models.TextField(),
        ),
    ]
